### ISSUE TITLE
Ошибка при установке руссификатора 1.4.2.

### ISSUE THREAD

**Issue by BytEvil** [AlexanderPro29/OctoPrint-RU-LangPack#2]
Привет! Ошибка при установке руссификатора 1.4.2 (Python 3.7.3)
`2020-10-05 14:01:38,732 - octoprint - ERROR - Exception on /api/languages [POST]
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/octoprint/server/util/flask.py", line 1315, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/octoprint/vendor/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/home/pi/OctoPrint/venv/lib/python3.7/site-packages/octoprint/server/api/languages.py", line 118, in uploadLanguagePack
    if not len(exts):
TypeError: object of type 'filter' has no len()`

**Comment by mirivlad** [comment]
Подтверждаю. Версия Octoprint 1.4.2, Python 3.8.5

**Comment by anonizmous** [comment]
то же самое. нет решения?

**Comment by BytEvil** [comment]
Решение есть, при ручной распаковке пакета все работает.

**Comment by EagleB3** [comment]
OctoPi 0.17.0, Octoprint 1.5.0, Python 3
Скачал ZIP и далее по тутошнему ReadMe
Все встало без вопросов. 

Спасибо автору!
